services:
  app:
    container_name: saung-rh-app-prod
    image: saung-rh-app:prod
    env_file:
      - ./.env
    volumes:
      - ${APP_PATH:-/opt/app/saung-rh-app}/public:/var/www/html/public
      - ${APP_STORAGE_PATH:-/opt/data/saung-rh-app/storage/app}:/var/www/html/storage/app
    build:
      context: ${APP_PATH:-.}
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/html
    expose:
      - "9000"
    networks:
      - default
      - app-network

  nginx:
    container_name: saung-rh-nginx-prod
    volumes:
      - /opt/data/certbot/etc:/etc/letsencrypt:ro
      - ${APP_PATH:-/opt/app/saung-rh-app}/public:/var/www/html/public:ro
      - ${APP_STORAGE_PATH:-/opt/data/saung-rh-app/storage/app}:/var/www/html/storage/app:ro
      - ${APP_PATH:-/opt/app/saung-rh-app}/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    image: nginx:1.27-alpine
    restart: unless-stopped
    depends_on:
      - app
    expose:
      - "80"
    networks:
      - default
      - app-network
  
  postgres:
    image: postgres:16
    container_name: postgres-main
    restart: unless-stopped
    
    ports:
      - "127.0.0.1:5432:5432"
      
    env_file:
      - .env

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: Asia/Jakarta

    volumes:
      - ${POSTGRES_DATA_PATH}:/var/lib/postgresql/data

    networks:
      - app-network

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  reverb:
    container_name: saung-rh-reverb-prod
    image: saung-rh-app:prod
    env_file:
      - ./.env
    command: php artisan reverb:start --host=0.0.0.0 --port=8080
    working_dir: /var/www/html
    restart: unless-stopped
    networks:
      - default
      - app-network

networks:
  app-network:
    external: true
